name: Lint
concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/lint.yml'
      - 'mk/**'
      - '.gitignore'
      - 'cobra.yml'
      - 'LICENSE'
      - 'Makefile'
      - 'README.md'
      - 'version'
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/lint.yml'
      - 'mk/**'
      - '.gitignore'
      - 'cobra.yml'
      - 'LICENSE'
      - 'Makefile'
      - 'README.md'
      - 'version'
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install Tools
        run: make install-tools
      - name: Run golangci-lint
        run: make lint
      - name: Run Deadcode
        run: make deadcode
